/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_system;

/**
 *
 * @author 94760
 */
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class employee extends javax.swing.JPanel {

    /**
     * Creates new form customer
     */
    public employee() {
        initComponents();
        tb_load();
    }
    public void tb_load(){
        try {
            DefaultTableModel tb=(DefaultTableModel)tbl_load.getModel();
            tb.setRowCount(0);
            
            //create statement
            Statement stmt=db.myCon().createStatement();
            String sql="SELECT * FROM employee";
            ResultSet rs=stmt.executeQuery(sql);
            
            while (rs.next()) {                
                
                Vector vec=new Vector();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(6));
                vec.add(rs.getString(8));

                tb.addRow(vec);
            }
        } catch (Exception e) {
            System.out.println(e);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_emp_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_emp_name = new javax.swing.JTextField();
        txt_emp_tp = new javax.swing.JTextField();
        txt_emp_nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_emp_hNo = new javax.swing.JTextField();
        txt_emp_fLane = new javax.swing.JTextField();
        txt_emp_lLane = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emp_search = new javax.swing.JButton();
        emp_update = new javax.swing.JButton();
        emp_save = new javax.swing.JButton();
        emp_delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cmb_emp_position = new javax.swing.JComboBox<>();
        btn_prod_clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_load = new javax.swing.JTable();

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setText("Search ID :");

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel9.setText("Employee Infomation:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Name :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Contact No :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 62, -1, -1));
        jPanel3.add(txt_emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 22, 252, -1));
        jPanel3.add(txt_emp_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 62, 252, -1));
        jPanel3.add(txt_emp_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 102, 252, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("NIC No :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 102, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Address :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 132, -1, -1));
        jPanel3.add(txt_emp_hNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 130, 193, -1));
        jPanel3.add(txt_emp_fLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 172, 198, -1));
        jPanel3.add(txt_emp_lLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 212, 198, -1));

        jLabel5.setText("House No");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 133, -1, -1));

        jLabel6.setText("2nd Lane");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 215, -1, -1));

        jLabel7.setText("1st Lane");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 175, -1, -1));

        emp_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-search-40.png"))); // NOI18N
        emp_search.setText("Search");
        emp_search.setToolTipText("");
        emp_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_searchActionPerformed(evt);
            }
        });
        jPanel3.add(emp_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 320, -1, -1));

        emp_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-update-40.png"))); // NOI18N
        emp_update.setText("Update");
        emp_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_updateActionPerformed(evt);
            }
        });
        jPanel3.add(emp_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 320, -1, -1));

        emp_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-save-40.png"))); // NOI18N
        emp_save.setText("Save");
        emp_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_saveActionPerformed(evt);
            }
        });
        jPanel3.add(emp_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 320, -1, -1));

        emp_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-delete-40.png"))); // NOI18N
        emp_delete.setText("Delete");
        emp_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(emp_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel10.setText("Position :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 252, -1, -1));

        cmb_emp_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Sales Leader", "Seler", " " }));
        cmb_emp_position.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_emp_positionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmb_emp_positionMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_emp_positionMouseReleased(evt);
            }
        });
        cmb_emp_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_emp_positionActionPerformed(evt);
            }
        });
        jPanel3.add(cmb_emp_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 252, 198, -1));

        btn_prod_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_prod_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-clear-40.png"))); // NOI18N
        btn_prod_clear.setText("Clear");
        btn_prod_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_prod_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 129, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tbl_load.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus ID", "Customer_Name", "Contact No", "NIC No", "Address", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_load);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emp_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_saveActionPerformed
        // store details in databse
        String emp_name=txt_emp_name.getText();
        String emp_tp=txt_emp_tp.getText();
        String emp_nic=txt_emp_nic.getText();
        String emp_hNo=txt_emp_hNo.getText();
        String emp_fLane=txt_emp_fLane.getText();
        String emp_lLane=txt_emp_lLane.getText();
        String emp_position=(String) cmb_emp_position.getSelectedItem();
        
        int result;
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="INSERT INTO employee(emp_Name,tp_No,NIC,h_No,f_Lane,l_Lane,position) VALUES ('"+emp_name+"','"+emp_tp+"','"+emp_nic+"','"+emp_hNo+"','"+emp_fLane+"','"+emp_lLane+"','"+emp_position+"')";
            result = stmt.executeUpdate(sql);
            if (result==1) {
                JOptionPane.showMessageDialog(null, "Data stored successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Data storage failed");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_emp_saveActionPerformed

    private void emp_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_searchActionPerformed
        //Search employee details
        
        String emp_id=txt_emp_id.getText();
         try {
            Statement stmt=db.myCon().createStatement();
            String sql= "SELECT * FROM employee WHERE (emp_ID = '"+emp_id+"') OR (NIC='"+emp_id+"')";
            ResultSet rs=stmt.executeQuery(sql);
             if (rs.next()) {
                txt_emp_name.setText(rs.getString("emp_Name"));
                txt_emp_tp.setText(rs.getString("tp_No"));
                txt_emp_nic.setText(rs.getString("NIC"));
                txt_emp_hNo.setText(rs.getString("h_No"));
                txt_emp_fLane.setText(rs.getString("f_Lane"));
                txt_emp_lLane.setText(rs.getString("l_Lane"));
                cmb_emp_position.setSelectedItem(rs.getString("position"));
             }
        } catch (Exception e) {
             System.out.println(e);
        }
         tb_load();
    }//GEN-LAST:event_emp_searchActionPerformed

    private void emp_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_updateActionPerformed
        // update employee details
        String emp_id=txt_emp_id.getText();
        
        String emp_name=txt_emp_name.getText();
        String emp_tp=txt_emp_tp.getText();
        String emp_nic=txt_emp_nic.getText();
        String emp_hNo=txt_emp_hNo.getText();
        String emp_fLane=txt_emp_fLane.getText();
        String emp_lLane=txt_emp_lLane.getText();
        String emp_position=(String) cmb_emp_position.getSelectedItem();
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="UPDATE employee SET emp_Name='"+emp_name+"' , tp_No='"+emp_tp+"' , NIC='"+emp_nic+"' , h_No='"+emp_hNo+"' , f_Lane='"+emp_fLane+"' , l_Lane='"+emp_lLane+"', position='"+emp_position+"' WHERE (emp_ID = '"+emp_id+"') OR (NIC='"+emp_id+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Updated");
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
        
    }//GEN-LAST:event_emp_updateActionPerformed

    private void emp_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_deleteActionPerformed
        // Delete employee details
        String emp_id=txt_emp_id.getText();
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="DELETE FROM employee WHERE (emp_ID = '"+emp_id+"') OR (NIC='"+emp_id+"')";
            stmt.executeUpdate(sql);
        } catch (Exception e) {
            System.out.println(e);
        }
        txt_emp_id.setText("");
        txt_emp_name.setText("");
        txt_emp_tp.setText("");
        txt_emp_nic.setText("");
        txt_emp_hNo.setText("");
        txt_emp_fLane.setText("");
        txt_emp_lLane.setText("");
        cmb_emp_position.setSelectedItem("");
        tb_load();
    }//GEN-LAST:event_emp_deleteActionPerformed

    private void tbl_loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loadMouseClicked
        int row=tbl_load.getSelectedRow();
        
        String id=tbl_load.getValueAt(row, 0).toString();
        String name=tbl_load.getValueAt(row, 1).toString();
        String tp=tbl_load.getValueAt(row, 2).toString();
        String nic=tbl_load.getValueAt(row, 3).toString();
        String address=tbl_load.getValueAt(row, 4).toString();
        String position=tbl_load.getValueAt(row, 5).toString();
        
        txt_emp_id.setText(id);
        txt_emp_name.setText(name);
        txt_emp_tp.setText(tp);
        txt_emp_nic.setText(nic);
        txt_emp_fLane.setText(address);
        cmb_emp_position.setSelectedItem(position);
    }//GEN-LAST:event_tbl_loadMouseClicked

    private void btn_prod_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_clearActionPerformed
        // claear type data
        txt_emp_id.setText("");
        txt_emp_name.setText("");
        txt_emp_tp.setText("");
        txt_emp_nic.setText("");
        txt_emp_hNo.setText("");
        txt_emp_fLane.setText("");
        txt_emp_lLane.setText("");
        cmb_emp_position.setSelectedIndex(4);
    }//GEN-LAST:event_btn_prod_clearActionPerformed

    private void cmb_emp_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_emp_positionActionPerformed
        //enter cashier Info
        String position=(String) cmb_emp_position.getSelectedItem();
        if(position.equals("Cashier")){
            cashierLog cLog=new cashierLog();
            cLog.setVisible(true);
        }
    }//GEN-LAST:event_cmb_emp_positionActionPerformed

    private void cmb_emp_positionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_emp_positionMouseClicked
        
        
    }//GEN-LAST:event_cmb_emp_positionMouseClicked

    private void cmb_emp_positionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_emp_positionMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_emp_positionMouseReleased

    private void cmb_emp_positionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_emp_positionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_emp_positionMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prod_clear;
    private javax.swing.JComboBox<String> cmb_emp_position;
    private javax.swing.JButton emp_delete;
    private javax.swing.JButton emp_save;
    private javax.swing.JButton emp_search;
    private javax.swing.JButton emp_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_load;
    private javax.swing.JTextField txt_emp_fLane;
    private javax.swing.JTextField txt_emp_hNo;
    private javax.swing.JTextField txt_emp_id;
    private javax.swing.JTextField txt_emp_lLane;
    private javax.swing.JTextField txt_emp_name;
    private javax.swing.JTextField txt_emp_nic;
    private javax.swing.JTextField txt_emp_tp;
    // End of variables declaration//GEN-END:variables
}
