/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_system;

/**
 *
 * @author 94760
 */
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class product extends javax.swing.JPanel {

    /**
     * Creates new form customer
     */
    public product() {
        initComponents();
        tb_load();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void tb_load(){
        try {
            DefaultTableModel tb=(DefaultTableModel)tbl_load.getModel();
            tb.setRowCount(0);
            
            //create statement
            Statement stmt=db.myCon().createStatement();
            String sql="SELECT * FROM product";
            ResultSet rs=stmt.executeQuery(sql);
            
            while (rs.next()) {                
                
                Vector vec=new Vector();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
                vec.add(rs.getString(6));
                
                tb.addRow(vec);
            }
        } catch (Exception e) {
            System.out.println(e);
            
        }
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_pro_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_pro_name = new javax.swing.JTextField();
        txt_pro_barNo = new javax.swing.JTextField();
        txt_pro_price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pro_qty = new javax.swing.JTextField();
        txt_pro_supID = new javax.swing.JTextField();
        btn_pro_search = new javax.swing.JButton();
        btn_pro_update = new javax.swing.JButton();
        btn_pro_save = new javax.swing.JButton();
        btn_pro_delete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_prod_clear = new javax.swing.JButton();
        txt_re_qun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_load = new javax.swing.JTable();
        txt_prod_search = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setText("Search ID :");

        jLabel9.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel9.setText("Product Infomation...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Name :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Bar No :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 102, -1, -1));
        jPanel3.add(txt_pro_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 22, 252, -1));
        jPanel3.add(txt_pro_barNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 191, -1));
        jPanel3.add(txt_pro_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 142, 131, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("Price :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 144, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Qty :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 180, -1, -1));
        jPanel3.add(txt_pro_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 178, 131, -1));
        jPanel3.add(txt_pro_supID, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 64, 245, -1));

        btn_pro_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pro_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-search-40.png"))); // NOI18N
        btn_pro_search.setText("Search");
        btn_pro_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_searchActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pro_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        btn_pro_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pro_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-update-40.png"))); // NOI18N
        btn_pro_update.setText("Update");
        btn_pro_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pro_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btn_pro_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pro_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-save-40.png"))); // NOI18N
        btn_pro_save.setText("Save");
        btn_pro_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pro_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btn_pro_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_pro_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-delete-40.png"))); // NOI18N
        btn_pro_delete.setText("Delete");
        btn_pro_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_pro_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel10.setText("Supplier ID :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 66, -1, -1));

        btn_prod_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_prod_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-clear-40.png"))); // NOI18N
        btn_prod_clear.setText("Clear");
        btn_prod_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_prod_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));
        jPanel3.add(txt_re_qun, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 211, 131, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setText("ReOrder Qty :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 208, -1, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tbl_load.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prod ID", "Prod_Name", "Bar code", "Price", "Qty", "Supplier_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_load);

        txt_prod_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_prod_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_prod_searchKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel11.setText("Search :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_prod_search, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_prod_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pro_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_saveActionPerformed
        // Save Product details
        String prod_Name=txt_pro_name.getText();
        String prod_BNo=txt_pro_barNo.getText();
        double prod_price=Double.parseDouble(txt_pro_price.getText());
        int prod_qty=Integer.parseInt(txt_pro_qty.getText());
        int sup_id=Integer.parseInt(txt_pro_supID.getText());
        int reQty=Integer.parseInt(txt_re_qun.getText());
        
        int result;
         try {
            Statement stmt=db.myCon().createStatement();
            String sql= "INSERT INTO product(prod_Name,bar_No,price,Qty,sup_ID,reOrder) VALUES ('"+prod_Name+"','"+prod_BNo+"','"+prod_price+"','"+prod_qty+"','"+sup_id+"','"+reQty+"')";
            result = stmt.executeUpdate(sql);
             if (result==1) {
                 JOptionPane.showMessageDialog(null, "Data stored successfully");
             }
             else{
                JOptionPane.showMessageDialog(null, "Data storage failed");
            }
        } catch (Exception e) {
             System.out.println(e);
        }
         tb_load();
    }//GEN-LAST:event_btn_pro_saveActionPerformed

    private void tbl_loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loadMouseClicked
        // get Data into textfield
        int row=tbl_load.getSelectedRow();
        
        String id=tbl_load.getValueAt(row, 0).toString();
        String name=tbl_load.getValueAt(row, 1).toString();
        String barNo=tbl_load.getValueAt(row, 2).toString();
        String price=tbl_load.getValueAt(row, 3).toString();
        String qty=tbl_load.getValueAt(row, 4).toString();
        String supId=tbl_load.getValueAt(row, 5).toString();
        
        
        txt_pro_id.setText(id);
        txt_pro_name.setText(name);
        txt_pro_barNo.setText(barNo);
        txt_pro_price.setText(price);
        txt_pro_qty.setText(qty);
        txt_pro_supID.setText(supId);
    }//GEN-LAST:event_tbl_loadMouseClicked

    private void btn_pro_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_searchActionPerformed
        // search product details
        String prod_id=txt_pro_id.getText();
        
        try {
            Statement stmt = db.myCon().createStatement();
            String sql="SELECT * FROM product WHERE (prod_ID = '"+prod_id+"') OR (bar_No='"+prod_id+"')";
            ResultSet rs = stmt.executeQuery(sql);
             if (rs.next()) {
                txt_pro_name.setText(rs.getString("prod_Name"));
                txt_pro_barNo.setText(rs.getString("bar_No"));
                txt_pro_price.setText(rs.getString("price"));
                txt_pro_qty.setText(rs.getString("Qty"));
                txt_pro_supID.setText(rs.getString("sup_ID"));
                txt_re_qun.setText(rs.getString("reOrder"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_btn_pro_searchActionPerformed

    private void btn_pro_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_updateActionPerformed
        // update product details
        String prod_id=txt_pro_id.getText();
        
        String prod_Name=txt_pro_name.getText();
        String prod_BNo=txt_pro_barNo.getText();
        double prod_price=Double.parseDouble(txt_pro_price.getText());
        int prod_qty=Integer.parseInt(txt_pro_qty.getText());
        int sup_id=Integer.parseInt(txt_pro_supID.getText());
        int reQty=Integer.parseInt(txt_re_qun.getText());
        
        try {
            Statement stmt = db.myCon().createStatement();
            String sql="UPDATE product SET prod_Name='"+prod_Name+"' , bar_No='"+prod_BNo+"' , price='"+prod_price+"' , Qty='"+prod_qty+"' , sup_ID='"+sup_id+"',reOrder='"+reQty+"' WHERE (prod_ID = '"+prod_id+"') OR (bar_No='"+prod_id+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Updated");
             
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_btn_pro_updateActionPerformed

    private void btn_pro_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_deleteActionPerformed
        //delete product details
        String prod_id=txt_pro_id.getText();
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="DELETE FROM product WHERE (prod_ID = '"+prod_id+"') OR (bar_No='"+prod_id+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Delete Success");
        } catch (Exception e) {
            System.out.println(e);
        }
        txt_pro_id.setText("");
        txt_pro_name.setText("");
        txt_pro_barNo.setText("");
        txt_pro_price.setText("");
        txt_pro_qty.setText("");
        txt_pro_supID.setText("");
        txt_re_qun.setText("");
        tb_load();

    }//GEN-LAST:event_btn_pro_deleteActionPerformed

    private void txt_prod_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prod_searchKeyPressed
        // serch text
        String serch=txt_prod_search.getText();
        try {
            DefaultTableModel tb_mode=(DefaultTableModel) tbl_load.getModel();
            Statement stmt=db.myCon().createStatement();
            tb_mode.setRowCount(0);
            String sql="SELECT * FROM product WHERE prod_Name LIKE '%"+serch+"%'";
            ResultSet rs=stmt.executeQuery(sql);
            
            while (rs.next()) {                
                Vector vec=new Vector();
                
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
                vec.add(rs.getString(6));
                
                tb_mode.addRow(vec);
            }
        } catch (Exception e) {
            tb_load();
        }
    }//GEN-LAST:event_txt_prod_searchKeyPressed

    private void btn_prod_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_clearActionPerformed
        // claear type data
        txt_pro_id.setText("");
        txt_pro_name.setText("");
        txt_pro_barNo.setText("");
        txt_pro_price.setText("");
        txt_pro_qty.setText("");
        txt_pro_supID.setText("");
        txt_re_qun.setText("");
    }//GEN-LAST:event_btn_prod_clearActionPerformed

    private void txt_prod_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prod_searchKeyReleased
         String serch=txt_prod_search.getText();
        try {
            DefaultTableModel tb_mode=(DefaultTableModel) tbl_load.getModel();
            Statement stmt=db.myCon().createStatement();
            tb_mode.setRowCount(0);
            String sql="SELECT * FROM product WHERE prod_Name LIKE '%"+serch+"%'";
            ResultSet rs=stmt.executeQuery(sql);
            
            while (rs.next()) {                
                Vector vec=new Vector();
                
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
                vec.add(rs.getString(6));
                
                tb_mode.addRow(vec);
            }
        } catch (Exception e) {
            tb_load();
        }
    }//GEN-LAST:event_txt_prod_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pro_delete;
    private javax.swing.JButton btn_pro_save;
    private javax.swing.JButton btn_pro_search;
    private javax.swing.JButton btn_pro_update;
    private javax.swing.JButton btn_prod_clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_load;
    private javax.swing.JTextField txt_pro_barNo;
    private javax.swing.JTextField txt_pro_id;
    private javax.swing.JTextField txt_pro_name;
    private javax.swing.JTextField txt_pro_price;
    private javax.swing.JTextField txt_pro_qty;
    private javax.swing.JTextField txt_pro_supID;
    private javax.swing.JTextField txt_prod_search;
    private javax.swing.JTextField txt_re_qun;
    // End of variables declaration//GEN-END:variables
}
