/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos_system;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.concurrent.locks.StampedLock;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 94760
 */
public class supplier extends javax.swing.JPanel {

    /**
     * Creates new form customer
     */
    public supplier() {
        initComponents();
        tb_load();
    }
        public void tb_load(){
        try {
            DefaultTableModel tb=(DefaultTableModel)tbl_load.getModel();
            tb.setRowCount(0);
            
            //create statement
            Statement stmt=db.myCon().createStatement();
            String sql="SELECT * FROM supplier";
            ResultSet rs=stmt.executeQuery(sql);
            
            while (rs.next()) {                
                
                Vector vec=new Vector();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(6));

                tb.addRow(vec);
            }
        } catch (Exception e) {
            System.out.println(e);
            
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_sup_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sup_cName = new javax.swing.JTextField();
        txt_sup_tp = new javax.swing.JTextField();
        txt_sup_regNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sup_hNo = new javax.swing.JTextField();
        txt_sup_fLane = new javax.swing.JTextField();
        txt_sup_lLane = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_sup_search = new javax.swing.JButton();
        btn_sup_update = new javax.swing.JButton();
        btn_sup_save = new javax.swing.JButton();
        btn_sup_delete = new javax.swing.JButton();
        btn_prod_clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_load = new javax.swing.JTable();

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setText("Search ID :");

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel9.setText("Supplier Infomation:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_sup_id, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_sup_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("Com.Name :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 42, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("Contact No :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 84, -1, -1));
        jPanel3.add(txt_sup_cName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 40, 233, -1));
        jPanel3.add(txt_sup_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 82, 233, -1));

        txt_sup_regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sup_regNoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_sup_regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 124, 238, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("REG No :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("Com.Address :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, -1, -1));
        jPanel3.add(txt_sup_hNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 166, 207, -1));
        jPanel3.add(txt_sup_fLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 208, 198, -1));
        jPanel3.add(txt_sup_lLane, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 248, 198, -1));

        jLabel5.setText(" No");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 169, -1, -1));

        jLabel6.setText("2nd Lane");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 251, -1, -1));

        jLabel7.setText("1st Lane");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 208, -1, -1));

        btn_sup_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sup_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-search-40.png"))); // NOI18N
        btn_sup_search.setText("Search");
        btn_sup_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sup_searchActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sup_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 306, -1, -1));

        btn_sup_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sup_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-update-40.png"))); // NOI18N
        btn_sup_update.setText("Update");
        btn_sup_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sup_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sup_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 306, -1, -1));

        btn_sup_save.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sup_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-save-40.png"))); // NOI18N
        btn_sup_save.setText("Save");
        btn_sup_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sup_saveActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sup_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 306, -1, -1));

        btn_sup_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sup_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-delete-40.png"))); // NOI18N
        btn_sup_delete.setText("Delete");
        btn_sup_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sup_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sup_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 306, -1, -1));

        btn_prod_clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_prod_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos_system/images/icons8-clear-40.png"))); // NOI18N
        btn_prod_clear.setText("Clear");
        btn_prod_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_clearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_prod_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 49, -1, -1));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tbl_load.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cus ID", "Supplier_Name", "Contact No", "NIC No", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_load.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_load);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sup_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sup_saveActionPerformed
        // save supplier details in Database
        //get data into variables
        
        String sup_name=txt_sup_cName.getText();
        String sup_tp=txt_sup_tp.getText();
        String sup_regNo=txt_sup_regNo.getText();
        String sup_hNo=txt_sup_hNo.getText();
        String sup_fLane=txt_sup_fLane.getText();
        String sup_lName=txt_sup_lLane.getText();
        
        //get connection
        int result;
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="INSERT INTO supplier(com_Name,tp,reg_No,h_No,f_lane,l_lane) VALUES ('"+sup_name+"','"+sup_tp+"','"+sup_regNo+"','"+sup_hNo+"','"+sup_fLane+"','"+sup_lName+"')";
            result = stmt.executeUpdate(sql);
            if (result==1) {
                JOptionPane.showMessageDialog(null, "Data stored successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Data storage failed");
            }
        } catch (Exception e) {
            System.out.println(e);
            
        }
        tb_load();
    }//GEN-LAST:event_btn_sup_saveActionPerformed

    private void btn_sup_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sup_searchActionPerformed
        // Searsh supllier details in suplier table
        String sup_id=txt_sup_id.getText();
        
        try {
            Statement stmt =db.myCon().createStatement();
            String sql="SELECT * FROM supplier WHERE (sup_ID = '"+sup_id+"') OR (reg_No='"+sup_id+"')";
            ResultSet rs=stmt.executeQuery(sql);
            if (rs.next ()) {
                txt_sup_cName.setText(rs.getString("com_Name"));
                txt_sup_tp.setText(rs.getString("tp"));
                txt_sup_regNo.setText(rs.getString("reg_No"));
                txt_sup_hNo.setText(rs.getString("h_No"));
                txt_sup_fLane.setText(rs.getString("f_lane"));
                txt_sup_lLane.setText(rs.getString("l_lane"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_btn_sup_searchActionPerformed

    private void btn_sup_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sup_updateActionPerformed
        //Update supplier details
        String sup_id=txt_sup_id.getText();
        
        String sup_name=txt_sup_cName.getText();
        String sup_tp=txt_sup_tp.getText();
        String sup_regNo=txt_sup_regNo.getText();
        String sup_hNo=txt_sup_hNo.getText();
        String sup_fLane=txt_sup_fLane.getText();
        String sup_lName=txt_sup_lLane.getText();
        
        try {
            Statement stmt = db.myCon().createStatement();
            String sql="UPDATE supplier SET com_Name='"+sup_name+"' , tp='"+sup_tp+"' , reg_No='"+sup_regNo+"' , h_No='"+sup_hNo+"' , f_lane='"+sup_fLane+"' , l_lane='"+sup_lName+"' WHERE (sup_ID = '"+sup_id+"') OR (reg_No='"+sup_id+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Updated");
        } catch (Exception e) {
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_btn_sup_updateActionPerformed

    private void btn_sup_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sup_deleteActionPerformed
        // delete details in database
        String sup_id=txt_sup_id.getText();
        
        try {
            Statement stmt=db.myCon().createStatement();
            String sql="DELETE FROM supplier WHERE (sup_ID = '"+sup_id+"') OR (reg_No='"+sup_id+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Delete Success");
        } catch (Exception e) {
        }
        txt_sup_id.setText("");
        txt_sup_cName.setText("");
        txt_sup_tp.setText("");
        txt_sup_regNo.setText("");
        txt_sup_hNo.setText("");
        txt_sup_fLane.setText("");
        txt_sup_lLane.setText("");
        tb_load();
    }//GEN-LAST:event_btn_sup_deleteActionPerformed

    private void tbl_loadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loadMouseClicked
        int row=tbl_load.getSelectedRow();
        
        String id=tbl_load.getValueAt(row, 0).toString();
        String name=tbl_load.getValueAt(row, 1).toString();
        String tp=tbl_load.getValueAt(row, 2).toString();
        String reg=tbl_load.getValueAt(row, 3).toString();
        String address=tbl_load.getValueAt(row, 4).toString();
        
        txt_sup_id.setText(id);
        txt_sup_cName.setText(name);
        txt_sup_tp.setText(tp);
        txt_sup_regNo.setText(reg);
        txt_sup_fLane.setText(address);
    }//GEN-LAST:event_tbl_loadMouseClicked

    private void btn_prod_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_clearActionPerformed
        // claear type data
        txt_sup_id.setText("");
        txt_sup_cName.setText("");
        txt_sup_regNo.setText("");
        txt_sup_tp.setText("");
        txt_sup_hNo.setText("");
        txt_sup_fLane.setText("");
        txt_sup_lLane.setText("");
    }//GEN-LAST:event_btn_prod_clearActionPerformed

    private void txt_sup_regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sup_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sup_regNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prod_clear;
    private javax.swing.JButton btn_sup_delete;
    private javax.swing.JButton btn_sup_save;
    private javax.swing.JButton btn_sup_search;
    private javax.swing.JButton btn_sup_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_load;
    private javax.swing.JTextField txt_sup_cName;
    private javax.swing.JTextField txt_sup_fLane;
    private javax.swing.JTextField txt_sup_hNo;
    private javax.swing.JTextField txt_sup_id;
    private javax.swing.JTextField txt_sup_lLane;
    private javax.swing.JTextField txt_sup_regNo;
    private javax.swing.JTextField txt_sup_tp;
    // End of variables declaration//GEN-END:variables
}
